language: python
python:
  - "3.7-dev"  # 3.7 development branch
before_script:
    - pip install --upgrade pip
    - pip install -r dev-requirements.txt
    - pip install .
# command to run tests
script:
  - python setup.py install
